[package]
name = "nats"
version = "0.7.4"
description = "A Rust NATS client"
authors = ["Derek Collison <derek@nats.io>", "Tyler Neely <tyler@nats.io>", "Stjepan Glavina <stjepan@nats.io>"]
edition = "2018"
license = "Apache-2.0"
documentation = "https://docs.rs/nats"
homepage = "https://github.com/nats-io/nats.rs"
repository = "https://github.com/nats-io/nats.rs"
readme = "README.md"
keywords = ["nats", "client", "messaging", "api"]
categories = ["network-programming", "api-bindings"]

[features]
fault_injection = []

[badges]
maintenance = { status = "actively-developed" }

[profile.dev]
panic = 'abort'

[dependencies]
async-channel = "1.2.0"
async-dup = "1.2.1"
async-mutex = "1.1.5"
async-tls = "0.8.0"
base64-url = "1.4.5"
crossbeam-channel = "0.4.2"
futures-channel = "0.3.5"
itoa = "0.4.6"
lazy_static = "1.4.0"
log = "0.4.8"
nkeys = "0.0.9"
nuid = "0.2.1"
once_cell = "1.4.0"
rand = "0.7.3"
regex = "1.3.9"
rustls = "0.18.0"
rustls-native-certs = "0.4.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
smol = "0.3.3"

[dev-dependencies]
criterion = "0.3.3"
env_logger = "0.7.1"
quicli = "0.4.0"
structopt = "0.3.15"
nats_test_server = { path = "nats_test_server" }

[[bench]]
name = "nats_bench"
harness = false

[[example]]
name = "nats-box"
path = "examples/nats-box/main.rs"

[[example]]
name = "serde-json"
path = "examples/serde-json/main.rs"
